### ISSUE TITLE
pip install fails on Python 3.6

### ISSUE THREAD

**Issue by gtaylor** [wavefrontHQ/wavefront-cli#10]
It looks like you support Python 3.4 (per setup.py), figured I'd mention that I was running into the following on Python 3.6 in case you were interested tweaking for 3.6:

```
(wavefront) [greg.taylor@riggs builder]$ pip install wavefront-cli
Collecting wavefront-cli
  Downloading https://files.pythonhosted.org/packages/18/d3/cafa4a02e3dc725b4321455d6ebc47720ebd037191a76003e8f1048d8129/wavefront_cli-0.0.113-py2.py3-none-any.whl
Collecting requests (from wavefront-cli)
  Downloading https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl (91kB)
    100% |████████████████████████████████| 92kB 7.8MB/s 
Collecting boto (from wavefront-cli)
  Downloading https://files.pythonhosted.org/packages/bd/b7/a88a67002b1185ed9a8e8a6ef15266728c2361fcb4f1d02ea331e4c7741d/boto-2.48.0-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 10.1MB/s 
Collecting importlib (from wavefront-cli)
  Downloading https://files.pythonhosted.org/packages/31/77/3781f65cafe55480b56914def99022a5d2965a4bb269655c89ef2f1de3cd/importlib-1.0.4.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/greg.taylor/.virtualenvs/wavefront/lib/python3.6/site-packages/setuptools/__init__.py", line 5, in <module>
        import distutils.core
      File "/home/greg.taylor/.virtualenvs/wavefront/lib/python3.6/distutils/__init__.py", line 4, in <module>
        import imp
      File "/home/greg.taylor/.virtualenvs/wavefront/lib/python3.6/imp.py", line 19, in <module>
        from importlib._bootstrap import _ERR_MSG, _exec, _load, _builtin_from_name
    ModuleNotFoundError: No module named 'importlib._bootstrap'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ams4rcd5/importlib/
```

**Comment by vikramraman** [comment]
Thanks for reporting the issue @gtaylor . We will look into it.

**Comment by kirilvasilev** [comment]
Any update on the issue?

**Comment by yogeshprasad** [comment]
This is failing because pip is trying to install the **importlib** package while installing the wavefront-cli as mentioned in the setup.py but for python 3  **importlib** is available by default as it is a  part of **Standard Library**

**Comment by skkli** [comment]
so, what should i do to fix it?
(i am a rookie

**Comment by yogeshprasad** [comment]
@skkli It has been already fixed and can be closed.
